### ISSUE TITLE
pm2.5传感器 分词不正确

### ISSUE THREAD

**Issue by XIAOYAYAYAYA** [blueshen/ik-analyzer#3]
如题，本人在主词典中添加  “pm2.5传感器” ，分词结果为 “pm2.5,传,感,器”，而不是一个完整的词，将 “pm2.5传感器” 放在扩展词库中也不能生效，但是，当在主词典中添加 “pm25传感器” 没有之前的小数点后，分词结果就正确了，返回了一个完整的词 “pm25传感器”，请问，分词结果跟 词中的 小数点有什么具体的关系吗？这种情况下应该如何解决这个问题？

**Comment by catBigcat** [comment]
可能和停用词有关。

**Comment by blueshen** [comment]
小数点默认被认为是分隔符了，这个严格意义上不算是一个BUG

**Comment by EricFangtasia** [comment]
你好，请问这么在配置文件里配置热更新词库
