### ISSUE TITLE
Cannot resolve org.wltea.ik-analyzer:ik-analyzer:8.4.0

### ISSUE THREAD

**Issue by rocalex** [blueshen/ik-analyzer#6]
I've met this error while building a demo application.
Added dependency like README
```
<dependency>
    <groupId>org.wltea.ik-analyzer</groupId>
    <artifactId>ik-analyzer</artifactId>
    <version>8.4.0</version>
</dependency>
```
How to resolve this issue?

**Comment by PriestTomb** [comment]
I guess the only method is clone the source code, and package/install by yourself.

**Comment by blueshen** [comment]
please mvn install to your local
