### ISSUE TITLE
Request to release ik-analyzer 9.0.0 to Maven Central Repository

### ISSUE THREAD

**Issue by JohnNiang** [blueshen/ik-analyzer#7]
### Describe this feature

Hi @blueshen , I noticed that we have supported ik-analyzer 9.0.0 for a long time at https://github.com/blueshen/ik-analyzer/commit/43bf6752ad14dfa1dbd503831b6c033b4ba9e955. It would be helpful for everyone who want to try it out by importing Maven dependency insteand of installing to local environment to release it to Maven Central Repository.

Thanks a lot!

**Comment by blueshen** [comment]
@JohnNiang I will fix it soon, group id will change to my own(cn.shenyanchao)

**Comment by blueshen** [comment]
<dependency>
        <groupId>cn.shenyanchao.ik-analyzer</groupId>
        <artifactId>ik-analyzer</artifactId>
        <version>9.0.0</version>
    </dependency>
    
    Done

**Comment by JohnNiang** [comment]
Thank @blueshen for your effort again!
